feat: table component
union-group/FRONT-1-vxtel pull request #33
Opened 2022-06-15 14:19 UTC by andresiqueira

Criação do component table, por favor, veja se está de acordo

2022-06-15 23:45 UTC, d3vlopes requested changes
Da uma olhadinha aqui nas mudanças
https://gist.github.com/d3vlopes/c82354582186ea6938fce93b68d09d50

2022-06-15 23:45 UTC, d3vlopes commented on src/components/Table/index.tsx
> +}
Vou deixar direitinho as mudanças nos comentários

2022-06-16 21:24 UTC, andresiqueira commented
as modificações solicitadas foram feitas, dá uma olhada aí...

2022-06-16 22:09 UTC, d3vlopes approved these changes

2022-06-16 22:09 UTC, merged